name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Install dependencies
      run: npm install
      
    - name: Execute linting scripts
      run: npm run lint
      
    #- name: Tests 
      #run: npm run test

    - name: Build
      run: npm run build
    
    - name: "Deploy to Vercel"
      run: |
        prodRun=""
        if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
          prodRun="--prod"
        fi

        npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
